ASPdotNet_StringVerarbeitung/ASPdotNet_StringVerarbeitung/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ASPdotNet_StringVerarbeitung.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ASPdotNet_StringVerarbeitung/ASPdotNet_StringVerarbeitung/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.ComponentModel.DataAnnotations; // namespace for validation
using Microsoft.AspNetCore.Http;
using System.Text.RegularExpressions;

namespace ASPdotNet_StringVerarbeitung.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }


        /*
         *  Variablen 
         */
         // public Variablen auf die von der View aus zugegriffen wird
        [BindProperty]
        [Required(ErrorMessage = "Sie haben keine Zeichenkette eingegeben")]
        [RegularExpression(@"(\w+\s+){9}\w.*", ErrorMessage = "Upps. Sie haben zu wenig Wörter eingegeben.")]
        public string inputString { get; set; } // eingegebene Zeichenkette
        public bool activated = false; // Variable, ob die Anwendung schon einmal ausgeführt wurde oder nicht
        public bool started = false; // Startvariable, um die eigentliche Anwendung anzuzeigen
        public List<List<string>> historyOutput = new List<List<string>>(); // Output der Historie
        // Anzahl der ersetzten Vokale
        public int aNum = 0;
        public int eNum = 0;
        public int iNum = 0;
        public int oNum = 0;
        public int uNum = 0;
        [ViewData]
        public string newString { get; set; } // überarbeitete Zeichenkette
        [ViewData]
        public int wordNum { get; set; } // Anzahl der eingegebenen Wörter

        // Variablen die nur im Page Modell existieren
        char[] vokale = { 'a', 'e', 'o', 'u' }; 
        string[] words = { };
        List<string> historyEntry = new List<string>();
        // Historie als statische Variable, damit sie auch nach einem POST beständig ist
        static List<List<string>> history = new List<List<string>>();


        // Starten der Anwendung, um das Eignabeformular anzuzeigen
        public IActionResult OnPostStarting()
        {
            started = true;
            return Page();
        }

        // Verarbeitung der eingegebenen Zeichenkette
        public IActionResult OnPostProcessing()
        {
            started = true;
            activated = true;

            // Die clientseitige Validierung schlägt z. B. nicht zu, wenn nur Leerzeichen eingegeben wurden
            if (inputString != null)
            {
                // splittet den String an einem Leerzeichen. Würde bei einem String der nur aus Leerzeichen besteht auf einen Fehler laufen
                words = inputString.Split(" ");
                // Wenn das "exit" eingegeben wird soll die Anwendung beendet werden, auch wenn < 10 Wörter eingegeben wurden.
                if (words.Contains("exit"))
                {
                    history = new List<List<string>>();
                    return RedirectToPage("/index");
                }
            }

            // War die Validierung positiv?
            if (ModelState.IsValid)
            {
                // Groß- & Kleinschreibung soll nicht beachtet werden
                inputString = inputString.ToLower();
                
                wordNum = words.Length;

                // Zählen der enthaltenden Vokale
                aNum = inputString.Split('a').Length - 1;
                eNum = inputString.Split('e').Length - 1;
                oNum = inputString.Split('o').Length - 1;
                uNum = inputString.Split('u').Length - 1;

                // Anzahl der Wörter
                wordNum = words.Length;

                // iterieren über jeden Buchstaben der eingegebenen Zeichenkette
                foreach (var character in inputString)
                {
                    // Wenn ein Buchstabe mit einem Vokal identisch ist, wird er durch ein i ersetzt
                    if (vokale.Contains(character))
                    {
                        newString += 'i';
                    }
                    else
                    {
                        newString += character;
                    }
                }
            }
            // Hinzufügen der Werte in die Historie
            historyEntry.Add(inputString);
            historyEntry.Add(newString);
            history.Add(historyEntry);
            // Erstellung einer "Output"-Variable, auf die innerhalb der View zugegriffen werden kann
            historyOutput = history;

            return Page();
        }

        // Beenden der Anwendung, indem die Indexseite zurückgegeben wird und die Historie gelöscht wird
        public IActionResult OnPostExitPage()
        {
            history = new List<List<string>>();
            return RedirectToPage("/index");
        }

    }
}

ASPdotNet_StringVerarbeitung/ASPdotNet_StringVerarbeitung/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ASPdotNet_StringVerarbeitung.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ASPdotNet_StringVerarbeitung/ASPdotNet_StringVerarbeitung/Pages/test.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using System.ComponentModel.DataAnnotations;

namespace ASPdotNet_StringVerarbeitung.Pages
{
    public class testModel : PageModel
    {
        [BindProperty]
        [Required]
        [RegularExpression(@"(.*\s){9}..*")]
        public string inputString { get; set; }

        bool startup = true;
        string newString = "";
        char[] vokale = { 'a', 'e', 'i', 'o', 'u' };
        char newChar = ' ';



        /* Methoden */
        public void OnGet()
        {

        }

        public IActionResult OnPost()
        {
            startup = false;
            string[] words = inputString.Split(" ");
            int wordNum = words.Length;
            if (words.Contains("exit"))
            {
                return RedirectToPage("/index");
            }
            if (wordNum >= 10)
            {
                foreach (var character in inputString)
                {
                    if (vokale.Contains(character))
                    {
                        newChar = 'i';
                        newString += newChar;
                    }
                    else
                    {
                        newString += character;
                    }
                }
            }
            else
            {
                newString = "Sie müssen mindestens 10 Wörter eingeben," +
                    " um die App verwenden zu können. In Ihrer aktuellen " +
                    $"Zeichenkette befinden sich allerdings nur { wordNum } " +
                    "Wörter.";
            }
            ViewData["result"] = newString;
            return Page();
        }
    }
}

ASPdotNet_StringVerarbeitung/ASPdotNet_StringVerarbeitung/Pages/Index.cshtml
@page
@model IndexModel
@{
    //ViewData["Title"] = "Home page";
}



<!--Wurde die Anwendung über den Startbutton gestartet, wird die eigentliche Anwendung angezeigt-->
@if (@Model.started)
{
    <p class="paragraph">
        Bitte geben Sie hier eine beliebige Zeichenkette ein. In dieser werden dann alle Vokale durch "i" ersetzt. <br />
        <b>Hinweis: </b>Achten Sie darauf, dass die Zeichenkette <u>mindestens</u> aus 10 Wörtern besteht. <br />
        Sie können die Anwendung jederzeit beenden indem Sie das Wort "exit" eingeben. <br />
        Viel Spaß mit der App :-)
    </p>

    <br />
    <br />

    <!--Eingabeformular mit einer clientseitigen Validierung-->
    <form method="post" class="needs-validation" id="inputForm" novalidate>
        <div class="input-group">
            <!--Mit Bootstrap designtes Eingabefeld-->
            <div class="input-group-prepend">
                <span class="input-group-text">Zeichenkette</span>
            </div>
            <!--Wert des Eingabefeldes wird an das Page Model gebunden.
                textarea muss für die clientseitige Validierung mit "required gekennzeichnet werden"-->
            <textarea asp-for="inputString" placeholder="Zeichenkette eingeben" class="form-control shadow-lg" aria-label="inputString" id="inputString" required></textarea>
            <!--Wird beim Fehlschlagen der clientseitigen Validierung angezeigt-->
            <div class="invalid-feedback">
                Bitte geben Sie eine Zeichenkette ein. Sonst funktionert das Ganze nicht...
            </div>
        </div>
        <br />
    </form>
    <!--Exit Formular. Für das Beenden der Anwendung wird eine weitere POST-Anfrage benötigt-->
    <form method="post" id="exitForm"></form>
    <!--Damit die Buttons in einer Reihe angezeigt werden können, wurde sie von ihren Formularen getrennt. Den Buttons wird einzeln ihr jeweiliges Formular zugewiesen-->
    <div class="mb-5 pb-5">
        <!--Bestätigungs-Button löst die Handler Methode "Processing" aus-->
        <button type="submit" class="btn btn-outline-success ml-4 mr-4 w-25 mt-2 shadow-lg" asp-page-handler="Processing" form="inputForm">Absenden</button>
        <!--JS wurde benötigt, um das Eingabefeld vollständig bereinigen zu können (ansonsten wird nur auf den letzten Stand resettet, dieser verändert sich aber bei jeder weiteren POST-Anfrage)-->
        <button type="button" class="btn btn-outline-warning ml-4 mr-4 w-25 mt-2 shadow-lg" onclick="resettingButton()" form="inputForm">Zurücksetzen</button>
        <!--Exit Button löst Handler Methode "Exit Page" aus-->
        <button type="submit" class="btn btn-outline-danger ml-4 mr-4 w-25 mt-2 shadow-lg" asp-page-handler="ExitPage" form="exitForm">Exit</button>
    </div>

    <br />

    <!--War die serverseititge Validierung erfolgreich wird die überarbeitete Zeichenkette in einem Bootstrap Jumbotron Feld angezeigt-->
    @if (@ModelState.IsValid)
    {
        <div class="jumbotron jumbotron-fluid bg-success my-auto shadow-lg rounded p-4 mt-5 pt-5" id="jumbo">
            <h2 class="display-4 text-light mt-4 mb-4 text-left"> Überarbeitete Zeichenkette </h2>
            <div class="container h-100 d-flex text-left">
                <code class="lead text-light text-left">@ViewData["newString"]</code>
            </div>
        </div>
    }
    // war die Validierung negativ, das Input-Formular wurde aber schon einmal ausgeführt, wird eine individuelle Fehlermeldung angezeigt
    else if (!@ModelState.IsValid && @Model.activated)
    {
        <div class="jumbotron jumbotron-fluid bg-danger my-auto shadow-lg rounded p-4 text-light">
            <h2 class="display-4 mt-4 mb-4 text-left"> Überarbeitete Zeichenkette </h2>
            <div class="container h-100 d-flex text-left">
                <!--Ausgabe der serverseitigen Validierungs-Fehlermeldung-->
                <span class="lead validation rounded p-1 font-weight-normal text-light" asp-validation-for="inputString"></span>
            </div>
        </div>
    }
}
// Defaultmäßig wird erst mal die folgende Startseite angezeigt
else
{ 
    <form method="post">
        <!--Startknopf-->
        <button type="submit" id="startButton" class="btn btn-success btn-lg shadow-lg rounded" asp-page-handler="Starting">Anwendung starten</button>
    </form>
}

<br />

<!--Wurde die Anwendung schon einmal bestätigt wird die Historie in einer Tabelle angezeigt-->
@if (@Model.activated)
{
    <h2 class="display-4 mt-5 pt-5 mb-4">Historie</h2>
    <div class="table-responsive-sm shadow-lg">
        <table class="table table-hover table-striped table-bordered table-success text-light lead ">
            <thead class="bg-success">
                <tr>
                    <th scope="col">Eingegebene Zeichenkette</th>
                    <th scope="col">Überarbeitete Zeichenkette</th>
                </tr>
            </thead>
            <!--Über die history-Liste wird iteriert, um die Tabellenzellen zu erstellen-->
            @foreach (var entry in @Model.historyOutput)
            {
                <tbody bg-light text-dark>
                    <tr class="text-dark">
                        <td>@entry[0]</td>
                        <td>@entry[1]</td>
                    </tr>
                </tbody>
            }
        </table>
    </div>




    <!--Google Chart-->

    <!--Versteckte Input Felder, denen die Anzahl der erstezten Vokale zugewiesen wird-->
    <input type="hidden" value="@Model.aNum" id="aNum" />
    <input type="hidden" value="@Model.eNum" id="eNum" />
    <input type="hidden" value="@Model.iNum" id="iNum" />
    <input type="hidden" value="@Model.oNum" id="oNum" />
    <input type="hidden" value="@Model.uNum" id="uNum" />

    <!--JS, in dem die Werte der versteckten Input Felder ausgelesen werden, und danach der Chart initialisiert wird-->
    <script type="text/javascript" src="~/js/statistic.js"></script>

    <h2 class="display-4 mt-5 pt-5 mb-4">Statistik</h2>
    <!--Anzahl der eingegeben Wörter-->
    <p class="lead">Anzahl eingegebener Wörter = @ViewData["wordNum"]</p>
    <p>Hier erhalten Sie einen Überlblick, welche Vokale im letzten Durchlauf wie häufig durch den Vokal "i" ersetzt wurden.</p>
    <!--Visualisierung des Charts-->
    <div id="piechart" style="width: 100%; height: 500px;"></div>

}



<!--Bootstrap Client Side Validation-->
<script type="text/javascript" src="~/js/validation.js"></script>

ASPdotNet_StringVerarbeitung/ASPdotNet_StringVerarbeitung/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Portfolio Nr. 6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <!--Einbinden der neu erstellten CSS-->
    <link rel="stylesheet" href="~/css/style.css" />
    <!--Google chart-->
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
</head>
<!--Dunkles Design des Bodys-->
<body class="bg-dark">
    <!--Designen eines neuen sticky headers mit Bootstrap-Klassen-->
    <header class="sticky-top">
        <nav class="navbar navbar-inverse navbar-expand-sm bg-success navbar-dark shadow-lg z-depth-5">
            <div class="container-fluid">
                <div class="nav-header">
                    <a id="home" class="navbar-brand" href="/">Portfolio Nr. 6</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container text-light">
        <main role="main" class="pb-3">
            <!--Body soll mittig ausgerichtet sein-->
            <div class="text-center">
                <!--Jede Seite soll diese Überschrift beinhalten-->
                <h1 class="display-3"> Überprüfung und Verarbeitung eines Strings mit ASP.Net </h1>
                @RenderBody()
            </div>
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

ASPdotNet_StringVerarbeitung/ASPdotNet_StringVerarbeitung/Pages/stringProcessing.cshtml
@page
@model ASPdotNet_StringVerarbeitung.Pages.stringProcessingModel
@{
}

<h1 class="display-4"> Überprüfung und Verarbeitung eines Strings mit ASP.Net </h1>
<form method="post">
    <p id="introduction">
        Bitte geben Sie hier eine beliebige Zeichenkette ein. <br /> <br />
        <b>Hinweis: </b>Achten Sie darauf, dass die Zeichenkette <u>mindestens</u> aus 10 Wörtern besteht. <br /> <br />
        Viel Spaß mit der App :-)
    </p>
    <p>
        Zeichenkette:
        <textarea asp-for="inputString" placeholder="Zeichenkette eingeben"></textarea> <br />
        <span class="validation" asp-validation-for="inputString"></span>
    </p><br />
    <button type="submit">Absenden</button>
</form>

<h2 class="display-4"> Überarbeitete Zeichenkette </h2>
@if (true)
{
    <p>Neue Zeichenkette: @ViewData["result"]</p>
}
else
{
    <p>Es wurde noch keine Zeichenkette eingegeben.</p>
    <p></p>
}